[versions]
# Kotlin & Android
kotlin = "1.9.23"
android-gradle-plugin = "8.10.1"

# Compose
compose = "1.6.6"
compose-material3 = "1.2.1"

# Dependency Injection
hilt = "2.51.1"

# Firebase
firebase-bom = "32.8.1"
google-services = "4.3.15"

# Room
room = "2.6.1"

# Coroutines
coroutines = "1.7.3"

# Retrofit & OkHttp
retrofit = "2.9.0"
okhttp = "4.11.0"

# ZXing
zxing = "3.5.2"

# Coil
coil = "2.4.0"

# CameraX
camera = "1.2.3"

# Navigation
navigation = "2.7.1"

# Accompanist
accompanist = "0.33.2-alpha"

# WorkManager
androidx-work = "2.9.0"

# DataStore
datastore = "1.0.0"

# KSP
ksp = "2.0.21-1.0.27"

# Testing
junit = "4.13.2"
androidx-junit = "1.1.5"
espresso = "3.5.1"

[plugins]
# Android Gradle
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }

# Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Hilt / DI

dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
hilt-dagger = { id = "com.google.dagger.hilt.android", version.ref = "google-services" }

# Firebase
googleservices = { id = "com.google.gms.google-services", version.ref = "google-services" }

[libraries]
# Core Android
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.10.1" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.6.2" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.7.2" }

# Compose
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.1.0" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Firebase (use BOM in build.gradle.kts)
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore-ktx", version = "24.7.1" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx", version = "22.1.1" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage-ktx", version = "20.2.1" }

# Retrofit & OkHttp
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# Coil
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# ZXing
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }

# Coroutines
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }

# CameraX
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }

# Accompanist
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }

# DataStore
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# KSP

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }

[bundles]
room = ["room-runtime", "room-ktx"]
android-test = ["androidx-junit", "espresso-core"]
