[versions]
kotlin = "1.9.23"
android-gradle-plugin = "8.10.1"
compose = "1.5.11"
hilt = "2.51.1"
firebase-bom = "32.8.1"
room = "2.6.1"
google-services = "4.3.15"
platform = "1.0.0"
junit = "4.13.2"
androidx-junit = "1.1.5"
espresso = "3.5.1"
androidx-work = "2.9.0"


[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
googleservices = { id = "com.google.gms.google-services", version.ref = "google-services" }
android-hilt = { id = "dagger.hilt.android.plugin", version.ref = "hilt" }
kotlin-compose = { id = "org.jetbrains.kotlin.android.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version = "2.51.1" }

[libraries]
# Core Android
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.10.1" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.6.2" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.7.2" }

# WorkManager
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }

# Compose
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.2.1" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.0.0" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version = "2.7.1" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-compose-material3-windowSize = "androidx.compose.material3:material3-window-size-class:1.0.1"

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.1.0" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Firebase BOM and libraries
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx", version = "20.2.0" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version = "24.7.1" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version = "22.1.1" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version = "20.2.1" }

# Coroutines
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.7.3" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version = "1.7.3" }

# CameraX and Barcode Scanning
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version = "1.2.3" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version = "1.2.3" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version = "1.2.3" }
barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version = "17.0.3" }

# Image loading
coil-compose = { group = "io.coil-kt", name = "coil-compose", version = "2.4.0" }

# Testing
junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.1.5" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.5.1" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
androidx-ui-tooling-debug = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
platform = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "platform" }
androidx-ui = "androidx.compose.ui:ui:1.4.0"
material3 = "androidx.compose.material3:material3:1.1.0"
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-ui-tooling-preview = "androidx.compose.ui:ui-tooling-preview:1.4.3"
materiL3 = "androidx.compose.material3:material3:1.2.1"
compose-ui = "androidx.compose.ui:ui:1.4.3"
compose-ui-tooling = "androidx.compose.ui:ui-tooling:1.4.3"
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version = "1.6.0" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version = "1.6.0" }



[bundles]
room = ["room-runtime", "room-ktx"]
android-test = ["androidx-junit", "espresso-core"]
